run:
  timeout: 5m
  skip-files:
    - '(.+)_test\.go'

linters:
  disable-all: false
  enable:
    - dogsled
    - dupl
    - lll
    - whitespace
    - wsl
  disable:
    - noctx
    - musttag
  presets:
    - bugs
    - unused
  fast: false
