run:
  deadline: 1m

linters:
  disable-all: false
  enable:
    - dogsled
    - dupl
    - lll
    - whitespace
    - wsl
  disable:
    - noctx
    - musttag
  presets:
    - bugs
    - unused
  fast: false
